apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-aggregate-prometheus=allowed'
      to the aggregate-prometheus.
  name: allow-to-aggregate-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-aggregate-prometheus: allowed
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          role: garden
      podSelector:
        matchLabels:
          app: aggregate-prometheus
          role: monitoring
  policyTypes:
  - Egress
  ingress: []