apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:privileged
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
