apiVersion: {{ include "rbacversion" .}}
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:psp:unprivileged
  annotations:
    gardener.cloud/description: |
      Allow all authenticated users to use the unprivileged PSP.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:unprivileged
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
