# Seed cluster registration manifest into which the control planes of Shoot clusters will be deployed.
---
apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: my-seed
spec:
  provider:
    type: <provider-name> # e.g., aws, azure, gcp, ...
    region: europe-1
# Optional, only needed if controlled by a Gardenlet running outside
# secretRef:
#   name: seed-secret
#   namespace: garden
# Configuration of backup object store provider into which the backups will be stored.
# If you don't want to have backups then don't specify the `.spec.backup` key.
  backup:
    provider: <provider-name> # e.g., aws, azure, gcp, ...
  # providerConfig:
  #   <some-provider-specific-config-for-the-backup-buckets>
    region: europe-1
    secretRef:
      name: backup-secret
      namespace: garden
  dns:
    ingressDomain: dev.my-seed.example.com
  networks: # seed and shoot networks must be disjunct
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
  # shootDefaults:
  #   pods: 100.96.0.0/11
  #   services: 100.64.0.0/13
    blockCIDRs:
    - 169.254.169.254/32
# taints:
# - key: seed.gardener.cloud/disable-dns                  # all shoots on this seed won't use any DNS, just the plain IPs/hostnames
# - key: seed.gardener.cloud/protected                    # only shoots in the `garden` namespace can use this seed
# - key: seed.gardener.cloud/invisible                    # the gardener-scheduler won't consider this seed for shoots
# - key: seed.gardener.cloud/disable-capacity-reservation # this seed will not deploy excess-capacity-reservation pods
# volume:
#  minimumSize: 20Gi
#  providers:
#  - purpose: etcd-main
#    name: flexvolume
