dependencies:
- name: cluster-autoscaler
  repository: http://localhost:10191
  version: 0.1.0
  condition: cluster-autoscaler.enabled
- name: coredns
  repository: http://localhost:10191
  version: 0.1.0
  condition: coredns.enabled
- name: kube-apiserver-kubelet
  repository: http://localhost:10191
  version: 0.1.0
  condition: kube-apiserver-kubelet.enabled
- name: kube-controller-manager
  repository: http://localhost:10191
  version: 0.1.0
  condition: kube-controller-manager.enabled
- name: kube-proxy
  repository: http://localhost:10191
  version: 0.1.0
  condition: kube-proxy.enabled
- name: kube-scheduler
  repository: http://localhost:10191
  version: 0.1.0
  condition: kube-scheduler.enabled
- name: metrics-server
  repository: http://localhost:10191
  version: 0.1.0
  condition: metrics-server.enabled
- name: monitoring
  repository: http://localhost:10191
  version: 0.1.0
  condition: monitoring.enabled
- name: network-policies
  repository: http://localhost:10191
  version: 0.1.0
  condition: network-policies.enabled
- name: node-problem-detector
  repository: http://localhost:10191
  version: 0.1.0
  condition: node-problem-detector.enabled
- name: podsecuritypolicies
  repository: http://localhost:10191
  version: 0.1.0
  condition: podsecuritypolicies.enabled
- name: shoot-info
  repository: http://localhost:10191
  version: 0.1.0
  condition: shoot-info.enabled
- name: vpn-shoot
  repository: http://localhost:10191
  version: 0.1.0
  condition: vpn-shoot.enabled
