kubernetesVersion: 1.13.1
replicas: 1
podAnnotations: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  kube-scheduler: image-repository
resources:
  requests:
    cpu: 23m
    memory: 64Mi
  limits:
    cpu: 400m
    memory: 512Mi
