apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: kube-state-metrics-seed
  namespace: {{ .Release.Namespace }}
  labels:
    component: kube-state-metrics
    type: seed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics-seed
  namespace: {{ .Release.Namespace }}
