apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-seed
  namespace: {{ .Release.Namespace }}
  labels:
    component: kube-state-metrics
    type: seed
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    component: kube-state-metrics
    type: seed
