
# configure default values for pull request tests
test:
  hostprovider: gke

  # uses the garden setup master to deploy gardener to the host clusters
  gardensetup:
    revision: "master"

  # deploys gardener with the pr's head commit version
  gardener:
    commit:
      prHead: true

  # gardener extensions to be deployed
  # will be merged with the default extensions defined in garden setup.
  gardener-extensions:
    value: |
      dns-external:
          repo: "https://github.com/gardener/external-dns-management.git"
          version: "latest"
      networking-calico:
          repo: "https://github.com/gardener/gardener-extension-networking-calico.git"
          version: "latest"
      os-coreos:
          repo: "https://github.com/gardener/gardener-extension-os-coreos.git"
          version: "latest"
      os-suse-jeos:
          repo: "https://github.com/gardener/gardener-extension-os-suse-jeos.git"
          version: "latest"
      os-ubuntu:
          repo: "https://github.com/gardener/gardener-extension-os-ubuntu.git"
          version: "latest"
      provider-aws:
          repo: "https://github.com/gardener/gardener-extension-provider-aws.git"
          version: "latest"
      provider-azure:
          repo: "https://github.com/gardener/gardener-extension-provider-azure.git"
          version: "latest"
      provider-gcp:
          repo: "https://github.com/gardener/gardener-extension-provider-gcp.git"
          version: "latest"
      provider-openstack:
          repo: "https://github.com/gardener/gardener-extension-provider-openstack.git"
          version: "latest"

  # test a gcp and aws shoot with version 1.15.5 by default with all gardener tests labeled default
  shootFlavors:
  - provider: gcp
    kubernetes:
      versions:
      - version: 1.15.5
  - provider: aws
    kubernetes:
      versions:
      - version: 1.15.5
