---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:system:project:{{ .Values.project.name }}
  ownerReferences:
  - apiVersion: core.gardener.cloud/v1beta1
    kind: Project
    blockOwnerDeletion: false
    controller: true
    name: {{ .Values.project.name | quote }}
    uid: {{ .Values.project.uid | quote }}
rules:
- apiGroups:
  - garden.sapcloud.io
  - core.gardener.cloud
  resources:
  - projects
  resourceNames:
  - {{ .Values.project.name | quote }}
  verbs:
  - get
  - patch
  - update
  - delete
