{{- range $i, $extension := .Values.project.extensions }}
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:extension:project:{{ $.Values.project.name }}:{{ $extension.name }}
  labels:
    gardener.cloud/role: extension-project-role
  ownerReferences:
  - apiVersion: core.gardener.cloud/v1beta1
    kind: Project
    blockOwnerDeletion: false
    controller: true
    name: {{ $.Values.project.name | quote }}
    uid: {{ $.Values.project.uid | quote }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.gardener.cloud/aggregate-to-extension-role: {{ $extension.name }}
rules: []
{{- end }}
