---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:system:project:{{ .Values.project.name }}
  ownerReferences:
  - apiVersion: core.gardener.cloud/v1beta1
    kind: Project
    blockOwnerDeletion: false
    controller: true
    name: {{ .Values.project.name | quote }}
    uid: {{ .Values.project.uid | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:system:project:{{ .Values.project.name }}
subjects:
{{ .Values.project.owner | list | toYaml }}
