---
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:system:project-member
  namespace: {{ .Release.Namespace }}
  ownerReferences:
  - apiVersion: core.gardener.cloud/v1beta1
    kind: Project
    blockOwnerDeletion: false
    controller: true
    name: {{ .Values.project.name | quote }}
    uid: {{ .Values.project.uid | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:system:project-member
{{- if .Values.project.members }}
subjects:
{{ toYaml .Values.project.members }}
{{- else }}
subjects: []
{{- end }}
