role: for-test
replicas: 1

images:
  etcd: image-repository:image-tag

storageCapacity: 16Gi

tlsServerSecretName: etcd-server-tls
tlsClientSecretName: etcd-client-tls
podAnnotations: {}
servicePorts:
  client: 2379
  server: 2380
  backuprestore: 8080

metrics: basic

scaleUpStabilization:
  stabilizationDuration: "5m"
  minChange:
    cpu:
      value: "1"
      percentage: 80
    memory:
      value: 2G
      percentage: 80

scaleDownStabilization:
  stabilizationDuration: "15m"
  minChange:
    cpu:
      value: "1"
      percentage: 80
    memory:
      value: 2G
      percentage: 80

targetAverageUtilizationCpu: 80
targetAverageUtilizationMemory: 80

maintenanceWindow: {}
# maintenanceWindow example:
#maintenanceWindow:
  #begin: 230000+0000
  #end: 000000+0000

etcdResources:
  requests:
    cpu: 300m
    memory: 1G
  limits:
    cpu: 900m
    memory: 3G

hvpa:
  enabled: false
  maxAllowed:
    cpu: "4"
    memory: 30G
  minAllowed:
    cpu: 200m
    memory: 700M

limitsRequestsGapScaleParams:
  cpu:
    value: "3"
    percentage: 80
  memory:
    value: "5G"
    percentage: 80