apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace:  kube-system
  annotations:
    resources.gardener.cloud/ignore: "true"
data:
  changeme.server: |
    # checkout the docs on how to use: https://github.com/gardener/gardener/blob/master/docs/usage/custom-dns.md
  changeme.override: |
    # checkout the docs on how to use: https://github.com/gardener/gardener/blob/master/docs/usage/custom-dns.md