
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:kube-proxy
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.kube-proxy
  resources:
  - podsecuritypolicies
  verbs:
  - use
